[package]
org = "ashen"
name = "webapp.backend"
version = "0.1.0"
distribution = "2201.9.0"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.3.0"


