[container.image]
repository="ghcr.io/ashen92/highlights"
name="highlights-api"
tag="latest"

[cloud.deployment]
min_memory="100Mi" # Minimum memory required for the container.
max_memory="256Mi" # Maximum memory a single container can take.
min_cpu="500m"  # Minimum CPU required for the container.
max_cpu="500m" # Maximum CPU a single container can take.

[cloud.deployment.autoscaling]
min_replicas=2 # Minimum number of container instances ran at a given time
max_replicas=5 # Maximum number of replicas of the container can scale up to
cpu=60 # Average CPU utilization of pods

[[cloud.config.files]] # Mounts the `Config.toml` file as a config map in Kubernetes.
file="./Prod.Config.toml"

[cloud.deployment.probes.liveness]
port=9092
path="/probes/healthz"

[cloud.deployment.probes.readiness]
port=9092
path="/probes/readyz"