apiVersion: v1
kind: Service
metadata:
  name: webapp-backend-svc
spec:
  selector:
    app: webapp-backend
  ports:
    - name: http
      protocol: TCP
      port: 80 # External port
      targetPort: 9090 # Internal port
    - name: ws
      protocol: TCP
      port: 81 # External port
      targetPort: 9091 # Internal port
  type: LoadBalancer
